Submit button made green
seattle-uat/civiform pull request #1270
Opened 2021-05-25 05:51 UTC by soham4abc

### Description
Submit button made green

### Checklist
- [ ] Created tests which fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

### Issue(s)
Fixes #1251

2021-05-25 16:57 UTC, kendrickt commented
(blocking) a screenshot would be handy in the PR description.

2021-05-26 04:38 UTC, soham4abc commented
> (blocking)
> 
> 1. a screenshot would be handy in the PR description.
> 2. We have a `views.style` package with classes like `AdminStyles` and `ApplicantStyles`. Styles should be configured there.
> 3. This change makes the button to create a new Trusted Intermediary green, which may not be what we want. The ticket is asking for making the application submit button green, which can be found in [`ApplicantProgramSummaryView`](https://github.com/seattle-uat/civiform/blob/aa0872c391193a759d61059ddc450c4afb40e293/universal-application-tool-0.0.1/app/views/applicant/ApplicantProgramSummaryView.java#L81) and uses [`ApplicantStyles#BUTTON_SUBMIT_APPLICATION`](https://github.com/seattle-uat/civiform/blob/aa0872c391193a759d61059ddc450c4afb40e293/universal-application-tool-0.0.1/app/views/style/ApplicantStyles.java#L108).

I got it but I am having issue while running the local server tying to run the `bin/run-dev` with docker but it's not working. Once done I will be able to give the Screenshot of my work.

2021-05-26 05:20 UTC, soham4abc commented
Hope this is what the issue requested.

2021-05-27 01:33 UTC, kendrickt requested changes

2021-05-27 01:33 UTC, kendrickt commented on universal-application-tool-0.0.1/app/views/style/ApplicantStyles.java
> +      StyleUtils.joinStyles(BUTTON_BASE_SOLID_UPPERCASE, Styles.TEXT_BASE, Styles.MX_AUTO,Styles.BG_GREEN_50);
(blocking) this is close, but BG_GREEN_50 is way too light to see. A screenshot of the page would be really helpful.

2021-05-27 06:46 UTC, soham4abc commented
I am trying to provide you a screenshot. But, whenever I run `bin/run-dev` even after successful compilation my `localhost:9000` remains unresponsive. Pls help me in this regard ![image.png](https://user-images.githubusercontent.com/63705023/119778531-476c4c00-bee5-11eb-8f5b-624b372b717d.png)

2021-05-27 09:46 UTC, soham4abc commented
Used bg-green-400 for better effect

2021-06-01 18:03 UTC, kendrickt requested changes
(blocking) it would really help to take a screenshot so you can see what this change looks like.

It would look something like this:
![image](https://user-images.githubusercontent.com/12072571/120369937-d7850980-c2c8-11eb-9144-d24b05896ab8.png)

The text and background does not have enough contrast, which makes the button hard to read.

Please choose an darker green, or keep the lighter green and make the text darker.

2021-06-02 05:01 UTC, soham4abc commented
> (blocking) it would really help to take a screenshot so you can see what this change looks like.
> 
> It would look something like this:
> ![image](https://user-images.githubusercontent.com/12072571/120369937-d7850980-c2c8-11eb-9144-d24b05896ab8.png)
> 
> The text and background does not have enough contrast, which makes the button hard to read.
> 
> Please choose an darker green, or keep the lighter green and make the text darker.

![image](https://user-images.githubusercontent.com/63705023/120426392-a3bfe780-c38d-11eb-8ded-241f5f84a1a5.png)

Used this darker green for better contrast hope it helps!

2021-06-02 17:10 UTC, kendrickt approved these changes
Looks good to me but you'll need to run `bin/fmt` to merge it in. Ping me in our slack space if you need some help with that.

2021-06-03 04:36 UTC, soham4abc commented
> Looks good to me but you'll need to run `bin/fmt` to merge it in. Ping me in our slack space if you need some help with that.
> 
> You'll see in the `Format (java) / formatting (pull_request)` is failing for this PR.

Done, Pls have a look!

2021-06-03 15:09 UTC, merged