File upload is required
seattle-uat/civiform pull request #1460
Opened 2021-06-23 22:24 UTC by hmhsu

### Description
Block upload if no file is selected.

### Checklist
- [ ] Created tests which fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

### Issue(s)
Fixes #<issue_number>; Fixes #<issue_number>; Fixes #<issue_number>...

2021-06-23 23:12 UTC, kendrickt commented on universal-application-tool-0.0.1/app/views/questiontypes/FileUploadQuestionRenderer.java
> +        .withClasses(ReferenceClasses.FILEUPLOAD_ERROR, Styles.TEXT_RED_600, Styles.HIDDEN);
(blocking) there's a `BaseStyles#FORM_ERROR_TEXT_BASE` or `#FORM_ERROR_TEXT_XS`.

2021-06-23 23:21 UTC, hmhsu commented on universal-application-tool-0.0.1/app/views/questiontypes/FileUploadQuestionRenderer.java
> +        .withClasses(ReferenceClasses.FILEUPLOAD_ERROR, Styles.TEXT_RED_600, Styles.HIDDEN);
Done.

2021-06-24 02:38 UTC, kendrickt requested changes
I'm just trying to block this in case you didn't see my slack message. I want to chat before this gets merged in.

2021-06-24 17:29 UTC, kendrickt approved these changes

2021-06-24 17:32 UTC, hmhsu commented
> I'm just trying to block this in case you didn't see my slack message. I want to chat before this gets merged in.

Chatted offline. Will have followup PRs to address some UX confusion.

2021-06-24 17:33 UTC, merged