Support to grant the log role assignment before writing to it
seattle-uat/civiform pull request #2117
Opened 2022-03-23 21:02 UTC by goldblatt

### Description
Adding an extra log method to call to set up permissions!

### Checklist
- [ ] Created tests which fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

### Issue(s)
Fixes #<issue_number>; Fixes #<issue_number>; Fixes #<issue_number>...

2022-03-23 22:20 UTC, goldblatt commented
fixes #2112

2022-03-24 23:26 UTC, bion requested changes

2022-03-24 23:26 UTC, bion commented on cloud/azure/bin/lib/azure_log.sh
> +function azure_log::grant_log_role_assignments() {
suggestion (blocking): recommend renaming to `ensure_log_role_assignments` since it does the check and bails if they already have it

2022-03-24 23:26 UTC, bion commented on cloud/azure/bin/lib/azure.sh
> +function azure::create_role_assignment() {
suggestion (blocking): recommend renaming to `ensure_role_assignment` since it does the check and bails if they already have it

2022-03-25 00:28 UTC, bion approved these changes

2022-03-25 07:19 UTC, shubha-rajan approved these changes

2022-03-25 07:19 UTC, shubha-rajan commented on cloud/azure/bin/lib/azure.sh
> +# Swap the canary slot into production.
Fix this docstring?

2022-03-25 23:41 UTC, merged