Adding visual indicator of whether a question is required or optional
seattle-uat/civiform pull request #2242
Opened 2022-04-01 19:09 UTC by gwendolyngoetz

Showing whether or not a question is required by adding an asterisk or optional text at the end of the question.

### Description
Moved the creation of the question text div into it's own method. Adding either an asterisk or optional text based on how the question is configured. The optional text pulls from messages so it can be localized.

Sample of rendered questions:

![image](https://user-images.githubusercontent.com/195162/161313870-c40f4334-d343-44db-ba63-d254451125ee.png)

### Checklist
- [ ] Created tests which fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

### Issue(s)
Fixes #1423

2022-04-06 00:05 UTC, shanemc-goog requested changes
Looks good, just need some tests.

2022-04-06 00:05 UTC, shanemc-goog commented on browser-test/src/program_deep_link.test.ts
> +      questionText + "*"
Note: I don't know if we handle RtL languages currently but if/when we do it'd be good to update this.

2022-04-06 00:05 UTC, shanemc-goog commented on universal-application-tool-0.0.1/app/views/questiontypes/ApplicantQuestionRenderer.java
> +  private ContainerTag createQuestionTextTag(Messages messages) {
I don't see any new tests for showing the correct thing in the correct instance.

2022-04-06 19:05 UTC, gwendolyngoetz commented on universal-application-tool-0.0.1/conf/messages
> +# The text shown next to a question indicating that it is optional
She's working on translations for me already

2022-04-27 22:09 UTC, bion commented
@gwendolyngoetz is it alright to put this PR back in draft mode?

2022-06-29 20:47 UTC, closed without merging