Adding create and last modified times to Program
seattle-uat/civiform pull request #2317
Opened 2022-04-20 18:42 UTC by azizova-leyla

### Description
Add create and last modified timestamps for programs.

![Screen Shot 2022-04-21 at 2 45 59 PM](https://user-images.githubusercontent.com/1741747/164563414-d006e34d-6d93-44cb-aff5-4634c95485a4.png)

### Checklist
- [ ] Created tests which fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

### Issue(s)
Fixes #1657; Does #2237 for Programs part.

2022-04-21 16:45 UTC, shanemc-goog commented
looking!

2022-04-21 19:53 UTC, shanemc-goog requested changes

2022-04-21 19:53 UTC, shanemc-goog commented on universal-application-tool-0.0.1/app/services/program/ProgramDefinition.java
> +  public abstract @Nullable Instant lastModifiedTime();
We want to prefer Optional over null as it makes the need to check for "is missing" clear and obvious.

We can't easily do that in the models files, or in data we serialize, but the sooner in the stack that we can start using Optional the better; like here.

2022-04-21 19:53 UTC, shanemc-goog commented on universal-application-tool-0.0.1/app/services/program/ProgramDefinition.java
> +  static final Instant DEFAULT_TIME = Instant.parse("2020-01-01T00:00:00.00Z");
Move this to the start of the class since it's a field and more so static.

2022-04-21 19:53 UTC, shanemc-goog commented on universal-application-tool-0.0.1/test/services/program/ProgramServiceImplTest.java
> +    assertThat(found.lastModifiedTime()).isNotEqualTo(originalProgram.lastModifiedTime());
suggestion: check that the new time is after the previous one for good measure.

2022-04-21 22:34 UTC, azizova-leyla commented on universal-application-tool-0.0.1/app/services/program/ProgramDefinition.java
> +  static final Instant DEFAULT_TIME = Instant.parse("2020-01-01T00:00:00.00Z");
removed this altogether in favor of optional and checking for presence.

2022-04-25 18:12 UTC, shanemc-goog approved these changes

2022-04-25 18:12 UTC, merged