Move checking question-requiredness into `getValidationErrors`. Only display validation errors on an unsuccessful attempt
seattle-uat/civiform pull request #2403
Opened 2022-05-02 16:13 UTC by clouser2

### Description
Previously, each question's validation only depended on whether the question was answered or not. This meant that calling getValidationErrors on a required, unanswered question would return success. Moving into QuestionImpl consolidates validation requirements.

With this change, rendering an edit block for the first time would have shown many validation errors for required fields. The question should always fail validation when required inputs aren't present, but likely shouldn't display until the applicant has attempted to submit. For this, I plumbed a parameter through indicating whether question validation errors. Rather than making each question renderer responsible for checking this, `ApplicantQuestionRendererImpl.render` passes validation errors to `renderTag` only if the parameter is set.

This is part of a larger sequence to remove client-side validation in #1944.

### Checklist
- [X] Created tests which fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

### Issue(s)
#1944

2022-05-02 17:15 UTC, bion requested changes

2022-05-02 18:32 UTC, clouser2 commented on server/app/views/applicant/ApplicantProgramBlockEditView.java
> +    public abstract boolean displayErrors();
Good suggestion. Done!

2022-05-02 18:50 UTC, bion submitted a review, later dismissed

2022-05-02 23:27 UTC, jeanniefu approved these changes

2022-05-03 16:18 UTC, bion approved these changes

2022-05-03 18:03 UTC, jeanniefu approved these changes

2022-05-03 18:09 UTC, merged