Clarify Azure CLI tool version requirements in instructions in cloud/shared/bin/doctor.
seattle-uat/civiform pull request #2420
Opened 2022-05-04 03:45 UTC by jeanniefu

2022-05-04 19:50 UTC, jeanniefu commented on cloud/shared/bin/lib/check_test.py
> +        self.assertTrue(check.version_at_least("1.0.4", "1.1.3"))
A bit hard to tell from the GitHub diffing, but this line I switched from "assertFalse" to "assertTrue".

2022-05-04 20:18 UTC, bion approved these changes

2022-05-05 19:32 UTC, goldblatt requested changes

2022-05-05 19:32 UTC, goldblatt commented on cloud/shared/bin/lib/check_test.py
> +    def test_version_at_least(self):
can we add a test for like 1.0.0 == 1

2022-05-10 03:27 UTC, jeanniefu commented on cloud/shared/bin/lib/check_test.py
> +    def test_version_at_least(self):
Done!

2022-05-10 03:27 UTC, jeanniefu commented on cloud/shared/bin/lib/check.py
> +            if i >= len(test_version) or min_int > test_version[i]:
Thank you, good catch! Used another variable. This does some unnecessary extra comparisons (e.g. we could terminate early for (1.0.0, 1) case), but I think it is clearer this way.

2022-05-13 21:08 UTC, clouser2 approved these changes

2022-05-16 18:53 UTC, goldblatt approved these changes

2022-05-18 17:59 UTC, merged