if there are multiple drafts for an application submit the latest one
seattle-uat/civiform pull request #2445
Opened 2022-05-05 19:24 UTC by azizova-leyla

### Description
If there are multiple drafts for a program - find the latest one and make that Active. Mark everything else Obsolete.
Also refactored tests to make them clearer.

### Checklist
- [ ] Created tests which fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

### Issue(s)
Fixes #<issue_number>; Fixes #<issue_number>; Fixes #<issue_number>...

2022-05-05 19:33 UTC, clouser2 approved these changes

2022-05-05 19:35 UTC, shanemc-goog commented
The title says application but the description says Program. Can you clarify those?

There should never be multiple drafts it's a violation of the System design, if there is that is a system crashing bug typically, and whatever is causing that state should be fixed.

Also what is the issue that this is trying to address?  I don't see a linked issue.

2022-05-05 20:05 UTC, azizova-leyla commented
> What is the issue that this is trying to address? I don't see a linked issue.
> 
> It'd be good to understand what puts the system in this incorrect state and address that up front. One issue could be if the "start" landing page is loaded in multiple tabs. We should likely address that case.

This is a hypothetical, I don't actually know how we would get to this state. Brett and I were doing a different change, and  saw this and it seemed that current handling could lead to errors if we ever have more than one draft for whatever reason.

2022-05-05 21:00 UTC, azizova-leyla commented
Suggestion from Bion: if this happens, throw 500. Don't try to gracefully recover.

2022-05-05 22:51 UTC, clouser2 approved these changes

2022-05-05 23:36 UTC, bion requested changes

2022-05-05 23:36 UTC, bion commented on server/app/repository/ApplicationRepository.java
> +                "Found more than one DRAFT application " + "for applicant %d, program %d.",
nit:
```suggestion
                "Found more than one DRAFT application for applicant %d, program %d.",
```

2022-05-05 23:36 UTC, bion commented on server/app/repository/ApplicationRepository.java
> +              .collect(Collectors.toList());
suggestion (blocking): prefer immutable collections from guava as a general rule
```suggestion
      ImmutableList<Application> latestDraft =
          oldApplications.stream()
              .filter(app -> app.getLifecycleStage().equals(LifecycleStage.DRAFT))
              .collect(ImmutableList.toImmutableList());
```

2022-05-05 23:36 UTC, bion commented on server/app/repository/ApplicationRepository.java
> +              : new Application(applicant, program, LifecycleStage.ACTIVE);
suggestion (blocking): reads a bit easier without the inversion
```suggestion
          latestDraft.isEmpty()
              ? new Application(applicant, program, LifecycleStage.ACTIVE)
              : latestDraft.get(0);
```

2022-05-06 00:38 UTC, bion approved these changes

2022-05-06 01:01 UTC, merged