Adding assertion to run-test-ci that test targets are actually found.
seattle-uat/civiform pull request #2474
Opened 2022-05-11 17:51 UTC by clouser2

### Description
Please explain the changes you made here.

### Checklist
- [ ] Created tests which fail without the change (if possible)
- [ ] Extended the README / documentation, if necessary

### Issue(s)
Fixes #<issue_number>; Fixes #<issue_number>; Fixes #<issue_number>...

2022-05-11 19:02 UTC, bion requested changes
Also need to update the workflow definition for junit tests

2022-05-11 19:02 UTC, bion commented on bin/run-test-ci
> +# Upon a successful test run (non-zero exit code), we also
```suggestion
# Upon a successful test run (exit code zero), we also
```

2022-05-11 21:04 UTC, clouser2 commented on bin/run-test-ci
> +# Upon a successful test run (non-zero exit code), we also
Done.

2022-05-11 21:05 UTC, clouser2 commented
> Also need to update the workflow definition for junit tests

Discussed offline. This is reusing the existing `run-test-ci` script, so there's no need to update the GitHub actions.

2022-05-11 23:47 UTC, bion approved these changes

2022-05-12 16:50 UTC, bion commented on bin/run-test-ci
> +${COMPOSE_CMD} exec civiform sbt "show Test/definedTestNames" | grep -iq "services.MessageKeyTest"
which other syntax?

2022-05-12 18:27 UTC, clouser2 commented on bin/run-test-ci
> +${COMPOSE_CMD} exec civiform sbt "show Test/definedTestNames" | grep -iq "services.MessageKeyTest"
Happy to switch to an alternative syntax if you can provide a code pointer to what it is.

2022-05-12 21:40 UTC, goldblatt commented on bin/run-test-ci
> +${COMPOSE_CMD} exec civiform sbt "show Test/definedTestNames" | grep -iq "services.MessageKeyTest"
https://www.baeldung.com/linux/store-command-in-variable; as found in cloud/shared/bin/lib/terraform.sh

2022-05-12 21:47 UTC, clouser2 commented on bin/run-test-ci
> +${COMPOSE_CMD} exec civiform sbt "show Test/definedTestNames" | grep -iq "services.MessageKeyTest"
Spoke offline about this and we're going to discuss applying this pattern to more of our files separately.

2022-05-12 21:48 UTC, goldblatt approved these changes

2022-05-12 21:49 UTC, merged