Ensure CSV exports write the header row even if there are no entries. Clean up internal implementation.
seattle-uat/civiform pull request #2734
Opened 2022-06-15 18:08 UTC by clouser2

### Description
Noticed as part of #1743. The interface for exporting CSVs didn't have clear separation of concerns or object lifecycle. We had logic to write the header row when writing the first record. While here, I took the opportunity to clean up the interface a bit:
  * Removed ExporterFactory, since it only has a single callsite
  * A `CSVExporter` wraps a `CSVPrinter` and implements `AutoClosable`. This means that the header row is written as part of the constructor (similar to the interface of `CSVPrinter`). This also means that we no longer have to pass a `Writer` to every invocation of a record, hopefully making the lifecycle clearer. 

### Checklist
- [X] Created tests which fail without the change (if possible)

### Issue(s)
 #1743

2022-06-15 18:10 UTC, clouser2 commented
Note: I expect the formatter to fail since it presently has a bug where it runs on deleted files. Sending a PR out for that shortly.

2022-06-15 18:11 UTC, clouser2 commented on server/app/services/export/CsvExporter.java
> -  public static final CSVFormat DEFAULT_CSV_FORMAT =
Note to the reviewer: This was unnecessarily shared between the implementation and the test.

2022-06-15 18:36 UTC, bion requested changes

2022-06-15 18:36 UTC, bion commented on server/app/services/export/CsvExporter.java
> +public final class CsvExporter implements AutoCloseable {
suggestion (blocking): update javadoc to mention the need to close

2022-06-15 18:36 UTC, bion commented on server/app/services/export/CsvExporter.java
>     */
suggestion (blocking): the comment for this method beginning with "The CSV exporter does not store the writer between calls." is a little strange now that the method doesn't take a writer. Please reword or remove

2022-06-15 18:36 UTC, bion commented on server/app/services/export/ExporterService.java
> +            .findFirst();
suggestion (non-blocking): i'm pretty sure that admin-specified, per-program export configuration was a planned feature that never got implemented. could remove this logic altogether if we wanted i think, though that may be refactor outside the scope of this PR

2022-06-15 23:10 UTC, bion approved these changes

2022-06-22 18:23 UTC, kmcnellis approved these changes

2022-06-22 18:23 UTC, kmcnellis commented on server/app/services/export/CsvExporter.java
> + * <p>The close method should be called when complete in order for the underlying {@link CsvPrinter}
According to the java docs, close is called automatically if you have a try-with-resources.  This comment seems a bit incorrect.  Could you modify it to say you need to either close() or  try-with-resources?

2022-06-23 16:15 UTC, merged